# Run using docker, not a VM
sudo: false

# Cache sbt downloaded packages
cache:
  directories:
    - $HOME/.sbt

# Now the actual core of the script
language: scala

scala:
  - 2.11.8

script:
  - sbt compile
  - sbt test
  - sbt scalastyle

# Send notifs to slack
notifications:
  slack:
    secure: "Qqx1Nu3CQrIxEpTo8uTD+eRi2z5dYjg1t7J2aEM+JW+rEGekL1NBtskqidOrPcJ0DbzicZ+9hfzGrNaeSSObMv8R217x65YTEyEz7qmS1XE9eE8WFjCRJMsG7XdSeWo0NEDC3g7DtlGFpeThgkElfHPv1A/npMcT5lIz23Ks/wLgXOrg56mm0bkgs4bVT/jrVcxgXgCTRf7t845z0llfwoN2m9oTjnC/VXJ9NPOMb5IDhoysLl5pKlESrSSWIa+M6fo/3JaGtx0Ih4M1ybAq//uhOtsqy+6nGdg3sR9KJAZUJURfG856YUJsUtfqGK4qzYsceweT+xaO+WMYzsmyYKhOBnxca6Nsn+/bDvZDOrcFIkQGfIpMnRpslpyRQQYnQ6P0PdvgF33pkBdfBSm0UKbNTjBoPMxXxXs+V8+0WQtd7mS6Sxaj3AXTg2lYH7eNgz3aEY0gcxHdM+ogt66lgZN5cMxXL3ny4GI2DFzNaf3sD1TRBFAd0kD4inR+WvM4qW1XBEKg7H2MMJTI07Cj+4cz9PLcRYqiZY6L5CXy12saEapMYse3BBZWTiQjLT6Rx26fBhwGVu6qDtCqjo2HVzGZw/8fmOPYTDhz+R/kq5bxiMYUzWzsY2MhK/M5XpAPLv3a3fwui2i707awMnAFcXXx7j6aMjTJwvYuPZmJb6U="
